type: object
oneOf:
  - $ref: '#/definitions/workflow'
  - $ref: '#/definitions/agent'

definitions:
  # Schema Definition of a Hive Agentic workflow
  workflow:
    type: object
    properties:
      kind:
        type: string
        const: workflow
      name:
        type: string
        description: "Unique name of the workflow"
      description:
        type: string
        description: "Description of the workflow's purpose"
      trigger:
        type: object
        description: "Defines how the workflow is triggered"
        properties:
          type:
            type: string
            description: "Type of trigger (e.g., webhook, scheduled)"
            enum: [webhook, scheduled]
          endpoint:
            type: string
            description: "Endpoint for webhook triggers"
          # Add other trigger-specific properties here (e.g., schedule for 'scheduled' type)
      additionalProperties:
        type: object
        description: "Named steps within the workflow"
        properties:
          type:
            type: string
            description: "Type of action to be performed in this step"
          description:
            type: string
            description: "Description of the step's purpose"
          input:
            type: string
            description: "Input data or reference to previous step output"
          output:
            type: string
            description: "Output data or variable name to store the result"
          condition:
            type: string
            description: "Conditional expression to determine if the step should execute"
          agent:
            type: string
            description: "Reference to an AI agent to execute in this step"
          tools:
            type: array
            description: "List of tools to be used in this step"
            items:
              type: string
              description: "Name of the tool"
          # Add other step-specific properties as needed (e.g., model, parameters, error handling)
    required:
      - kind
      - name
      - trigger

  # Schema Definition of a Hive AI Agent
  agent:
    type: object
    properties:
      kind:
        type: string
        const: agent  # Corrected this to 'agent'
      # ... (rest of the agent schema will be expanded in the next step)